# Generated by Django 5.2.5 on 2025-08-20 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bloco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_patrimonio', models.IntegerField(blank=True, null=True, unique=True)),
                ('capacidade_u', models.IntegerField(blank=True, null=True)),
                ('sala', models.CharField(max_length=50)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bloco')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_portas', models.SmallIntegerField()),
                ('num_patrimonio', models.IntegerField(unique=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.switch')),
            ],
        ),
    ]
