# Generated by Django 5.2.5 on 2025-09-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='data_registro',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='rack',
            new_name='id_rack',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='bloco',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='capacidade_u',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='sala',
        ),
        migrations.AddField(
            model_name='porta',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porta',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='localizacao',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='porta',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='inventario.switch'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='num_patrimonio',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='num_patrimonio',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='quantidade_portas',
            field=models.IntegerField(),
        ),
    ]
