# Generated by Django 5.2.5 on 2025-09-08 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_historico_modelo_historico_objeto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='porta',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='switch',
            name='id_rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='inventario.rack'),
        ),
    ]
