# Generated by Django 5.2.5 on 2025-09-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_historico_id_alter_porta_numero_alter_rack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='capacidade_u',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='id_bloco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventario.bloco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='sala',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
