# Generated by Django 5.2.5 on 2025-09-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rack_capacidade_u_rack_id_bloco_rack_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='localizacao',
        ),
    ]
