# Generated by Django 5.2.5 on 2025-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_rack_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porta',
            name='valor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
