# Generated by Django 5.2.5 on 2025-09-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_porta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='endereco_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
