# Generated by Django 5.2.5 on 2025-09-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_switch_descricao_switch_endereco_ip_switch_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='id_bloco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventario.bloco'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='num_patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='sala',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='num_patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
