# Generated by Django 5.2.5 on 2025-10-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_rack_id_bloco_alter_rack_num_patrimonio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='modelo',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='objeto_id',
        ),
    ]
