# Generated by Django 5.2.5 on 2025-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_rename_modelo_historico_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='orientacao',
            field=models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], default='H', max_length=1),
        ),
    ]
