# Generated by Django 5.2.5 on 2025-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_switch_orientacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porta',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
